web/router.ex
defmodule StaticBlog.Router do
  use StaticBlog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StaticBlog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/archives", PageController, :archives
    get "/:slug",  PostController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", StaticBlog do
  #   pipe_through :api
  # end
end

lib/static_blog/Crawler.ex
defmodule StaticBlog.Crawler do
	def crawl do
		File.ls!("priv/posts")
		|> Enum.map(fn(file) -> Task.async(fn -> StaticBlog.Post.compile(file) end) end)
		|> Enum.map(&Task.await/1)
		|> Enum.sort(&sort/2)
	end

	def sort(a, b) do
		Timex.compare(a.date, b.date) > 0
	end
end

lib/static_blog/Post.ex
defmodule StaticBlog.Post do
	defstruct slug: "", title: "", date: "", intro: "", content: "", img: "", author: ""

	def compile(file) do
		post = %StaticBlog.Post{
			slug: file_to_slug(file)
		}

		Path.join(["priv/posts", file])
		|> File.read!
		|> split
		|> extract(post)
	end

	defp file_to_slug(file) do
    	String.replace(file, ~r/\.md$/, "")
  	end

	defp split(data) do
		[frontmatter, markdown] = String.split(data, "\n---", parts: 2) #TODO: figure out the regex to do this.
		{parse_yaml(frontmatter), Earmark.to_html(markdown)}
	end

	defp parse_yaml(yaml) do
		[parsed] = :yamerl_constr.string(yaml)
		parsed
	end

	defp extract({props, content}, post) do
	    %{post |
	      title: get_prop(props, "title"),
	      date: Timex.parse!(get_prop(props, "date"), "{ISOdate}"),
	      intro: get_prop(props, "intro"),
	      content: content,
		  img: get_prop(props,"img"),
		  author: get_prop(props,"author")}
  	end

  	defp get_prop(props, key) do
  		case :proplists.get_value(String.to_char_list(key), props) do
  			:undefined -> nil
  			x -> to_string(x)
  		end
  	end
end

lib/static_blog/Repo.ex
defmodule StaticBlog.Repo do
	use GenServer

	def start_link do
		GenServer.start_link(__MODULE__, :ok, [name: __MODULE__])
	end

	def init(:ok) do
		posts = StaticBlog.Crawler.crawl
		{:ok, posts}
	end

	def get_by_slug(slug) do
		GenServer.call(__MODULE__, {:get_by_slug, slug})
	end

	def list() do
    	GenServer.call(__MODULE__, {:list})
  	end

	def handle_call({:get_by_slug, slug}, _from, posts) do
    	case Enum.find(posts, fn(x) -> x.slug == slug end) do
	      nil -> {:reply, :not_found, posts}
	      post -> {:reply, {:ok, post}, posts}
    	end
  	end

  	def handle_call({:list}, _from, posts) do
    	{:reply, {:ok, posts}, posts}
  	end
end

lib/static_blog/endpoint.ex
defmodule StaticBlog.Endpoint do
  use Phoenix.Endpoint, otp_app: :static_blog

  socket "/socket", StaticBlog.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :static_blog, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_static_blog_key",
    signing_salt: "ywy66vjj"

  plug StaticBlog.Router
end

web/controllers/page_controller.ex
defmodule StaticBlog.PageController do
	use StaticBlog.Web, :controller

  	def index(conn, _params) do
		{:ok, posts} = StaticBlog.Repo.list()
		render conn, "index.html", posts: posts
	end

  	def archives(conn, _params) do
		{:ok, posts} = StaticBlog.Repo.list()		
		render conn, "archives.html", posts: posts
	end

	def about(conn, _params) do
		render conn, "about.html"
	end
end

web/controllers/post_controller.ex
defmodule StaticBlog.PostController do
  use StaticBlog.Web, :controller

  def show(conn, %{"slug" => slug}) do
    case StaticBlog.Repo.get_by_slug(slug) do
      {:ok, post} -> render conn, "show.html", post: post
      :not_found -> not_found(conn)
    end
  end

  def not_found(conn) do
    conn
    |> put_status(:not_found)
    |> render(StaticBlog.ErrorView, "404.html")
  end
end

web/views/error_view.ex
defmodule StaticBlog.ErrorView do
  use StaticBlog.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule StaticBlog.LayoutView do
  use StaticBlog.Web, :view
end

web/views/page_view.ex
defmodule StaticBlog.PageView do
  use StaticBlog.Web, :view
end

web/views/post_view.ex
defmodule StaticBlog.PostView do
  use StaticBlog.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Home</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/bootstrap.min.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body class="blog-background">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a href="<%= page_path(@conn, :index) %>" class="navbar-brand">The Kellers Blog</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                    <li><a href="<%= page_path(@conn, :index) %>">Home</a></li>
                    <li><a href="<%= page_path(@conn, :about) %>">About</a></li>
                    <li><a href="<%= page_path(@conn, :archives) %>">Archives</a></li>
                  </ul>                  
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>
      <div class="container-fluid">
        <div class="row">
          <div class="blog-content col-md-offset-2 col-md-8">

                <p class="alert alert-info hidden" role="alert"><%= get_flash(@conn, :info) %></p>
                <p class="alert alert-danger hidden" role="alert"><%= get_flash(@conn, :error) %></p>

                <main role="main" class="content-body">
                  <%= render @view_module, @view_template, assigns %>
                </main>
          </div> 
        </div>     
      </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/jquery.min.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/bootstrap.min.js") %>"></script>
  </body>
</html>

web/templates/page/about.html.eex
<div class="row">
    <div class="col-md-12">
        <h2>Corey Keller</h2>
    </div>    
</div>
<hr/>

<div class="row">
    <div class="col-md-2 col-sm-2">
        <img src="<%= static_path(@conn, "/images/CoreyWebsite.jpg" )%>" alt="CoreyKeller" class="img-circle img-responsive">
    </div>
    <div class="col-md-10 col-sm-10">
        <p>My name is Corey Keller and I am a software engineer at Clear-Measure, a consulting company based in Austin Texas. 
        I primarily work on .NET web applications while learning Elixir and Erlang on my spare time.
        </p>
        <p>Github: <a href="https://github.com/cakeller43">cakeller43</a></p>
        <p>Twitter: <a href="https://twitter.com/TheKellerFeller">@TheKellerFeller</a></p>
        <p>LinkedIn: <a href="https://www.linkedin.com/in/corey-keller-512454b6/">Corey Keller</a></p>
        <p>Email: blog.thekellerfeller@gmail.com</p>
    </div>
</div>


<br>
<br>
<br>


<div class="row">
    <div class="col-md-12">
        <h2 class="pull-right">Curtis Keller</h2>
    </div>    
</div>

<hr/>

<div class="row">
    <div class="col-md-10 col-sm-10">
        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
    </div>
    <div class="col-md-2 col-sm-2">
        <img src="<%= static_path(@conn, "/images/CurtisWebsite.jpg" )%>" alt="CurtisKeller" class="img-circle img-responsive">
    </div>
</div>

web/templates/page/archives.html.eex
<h1>Archives</h1><hr/>
<%= for post <- @posts do %> 
    <div class="row">
    <div class="col-md-12 col-xs-12">
        <h4><%= Timex.format!(post.date, "{Mshort} {YYYY}") %></h4>
    </div>
    </div>
     <ul style="list-style: none">
        <li>
            <a class="btn btn-link" href="<%= post_path(@conn, :show, post.slug) %>"><%= post.title %></a>
        </li>
     </ul>
<% end %>   

web/templates/page/index.html.eex
<!--<div class="row">
  <div class="col-md-12">
      <span> This is the description</span>
  </div>
</div>-->
<%= for post <- @posts do %> 
  <div class="row">
  <div class="col-md-9 col-xs-9">
    <h2><%= post.title %></h2>
    <h4><%= post.author %> - <%= Timex.format!(post.date, "{Mshort} {D} {YYYY}") %></h4>
    
    <p><%= post.intro %></p>
  </div>
  <div class="col-md-3 hidden-xs">
      <img class="center-block resize-image" src="<%= static_path(@conn, post.img )%>" alt="postImage">
  </div>  
  <div class="hidden-lg hidden-md hidden-sm hidden-xl">
      <img class="center-block resize-image-xs" src="<%= static_path(@conn, post.img )%>" alt="postImage">
  </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <a class="btn btn-sm btn-primary" href="<%= post_path(@conn, :show, post.slug) %>">Read post</a>
    </div>
  </div>
  <hr/>
     
<% end %>    

web/templates/post/show.html.eex
<div class="post-body">
  <h1><%= @post.title %></h1>
  <h4><%= @post.author %></h4>  
  <p><%= Timex.format!(@post.date, "{Mshort} {D} {YYYY}") %></p>
  <hr/>
  <%= raw(@post.content) %>
</div>